### ISSUE TITLE
Missing tslib (or some other) dependency?

### ISSUE THREAD

**Issue by foolip** [sadym-chromium/bidiInChromeContext#10]
When running the tests I see this on the console of the server:

> Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?

The whole thing:
```
(node:62371) UnhandledPromiseRejectionWarning: Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
    at error (file:///Users/foolip/src/bidiInChromeContext/node_modules/rollup/dist/es/shared/rollup.js:5226:30)
    at throwPluginError (file:///Users/foolip/src/bidiInChromeContext/node_modules/rollup/dist/es/shared/rollup.js:18005:12)
    at Object.error (file:///Users/foolip/src/bidiInChromeContext/node_modules/rollup/dist/es/shared/rollup.js:18631:20)
    at preflight (/Users/foolip/src/bidiInChromeContext/node_modules/@rollup/plugin-typescript/dist/index.js:476:17)
    at Object.buildStart (/Users/foolip/src/bidiInChromeContext/node_modules/@rollup/plugin-typescript/dist/index.js:716:13)
    at file:///Users/foolip/src/bidiInChromeContext/node_modules/rollup/dist/es/shared/rollup.js:18835:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async rollupInternal (file:///Users/foolip/src/bidiInChromeContext/node_modules/rollup/dist/es/shared/rollup.js:20254:9)
    at async read (file:///Users/foolip/src/bidiInChromeContext/src/.build/mapperReader.js:20:20)
```

I don't see a direct dependency on tslib, but something seems to be missing?

**Comment by sadym-chromium** [comment]
Can I ask you to check now? It should be solved by https://github.com/sadym-chromium/bidiInChromeContext/commit/37819845405b893d455303805f783cb29054be7b

**Comment by foolip** [comment]
That fixed it! All 40 tests ran, 7 passed, and no logs emitted by the server.
